; Auto-generated. Do not edit!


(cl:in-package action2_pkg-msg)


;//! \htmlinclude demoFeedback.msg.html

(cl:defclass <demoFeedback> (roslisp-msg-protocol:ros-message)
  ((current_number
    :reader current_number
    :initarg :current_number
    :type cl:integer
    :initform 0))
)

(cl:defclass demoFeedback (<demoFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <demoFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'demoFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action2_pkg-msg:<demoFeedback> is deprecated: use action2_pkg-msg:demoFeedback instead.")))

(cl:ensure-generic-function 'current_number-val :lambda-list '(m))
(cl:defmethod current_number-val ((m <demoFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action2_pkg-msg:current_number-val is deprecated.  Use action2_pkg-msg:current_number instead.")
  (current_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <demoFeedback>) ostream)
  "Serializes a message object of type '<demoFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <demoFeedback>) istream)
  "Deserializes a message object of type '<demoFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_number) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<demoFeedback>)))
  "Returns string type for a message object of type '<demoFeedback>"
  "action2_pkg/demoFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'demoFeedback)))
  "Returns string type for a message object of type 'demoFeedback"
  "action2_pkg/demoFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<demoFeedback>)))
  "Returns md5sum for a message object of type '<demoFeedback>"
  "a34d09927bdf6eea84e4ff079b190b1d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'demoFeedback)))
  "Returns md5sum for a message object of type 'demoFeedback"
  "a34d09927bdf6eea84e4ff079b190b1d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<demoFeedback>)))
  "Returns full string definition for message of type '<demoFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedack~%int32 current_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'demoFeedback)))
  "Returns full string definition for message of type 'demoFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedack~%int32 current_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <demoFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <demoFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'demoFeedback
    (cl:cons ':current_number (current_number msg))
))
