// Generated by gencpp from file action2_pkg/demoFeedback.msg
// DO NOT EDIT!


#ifndef ACTION2_PKG_MESSAGE_DEMOFEEDBACK_H
#define ACTION2_PKG_MESSAGE_DEMOFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action2_pkg
{
template <class ContainerAllocator>
struct demoFeedback_
{
  typedef demoFeedback_<ContainerAllocator> Type;

  demoFeedback_()
    : current_number(0)  {
    }
  demoFeedback_(const ContainerAllocator& _alloc)
    : current_number(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_number_type;
  _current_number_type current_number;





  typedef boost::shared_ptr< ::action2_pkg::demoFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action2_pkg::demoFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct demoFeedback_

typedef ::action2_pkg::demoFeedback_<std::allocator<void> > demoFeedback;

typedef boost::shared_ptr< ::action2_pkg::demoFeedback > demoFeedbackPtr;
typedef boost::shared_ptr< ::action2_pkg::demoFeedback const> demoFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action2_pkg::demoFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action2_pkg::demoFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action2_pkg::demoFeedback_<ContainerAllocator1> & lhs, const ::action2_pkg::demoFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_number == rhs.current_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action2_pkg::demoFeedback_<ContainerAllocator1> & lhs, const ::action2_pkg::demoFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action2_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action2_pkg::demoFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action2_pkg::demoFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action2_pkg::demoFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action2_pkg::demoFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action2_pkg::demoFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action2_pkg::demoFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action2_pkg::demoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a34d09927bdf6eea84e4ff079b190b1d";
  }

  static const char* value(const ::action2_pkg::demoFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa34d09927bdf6eeaULL;
  static const uint64_t static_value2 = 0x84e4ff079b190b1dULL;
};

template<class ContainerAllocator>
struct DataType< ::action2_pkg::demoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action2_pkg/demoFeedback";
  }

  static const char* value(const ::action2_pkg::demoFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action2_pkg::demoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedack\n"
"int32 current_number\n"
;
  }

  static const char* value(const ::action2_pkg::demoFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action2_pkg::demoFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct demoFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action2_pkg::demoFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action2_pkg::demoFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION2_PKG_MESSAGE_DEMOFEEDBACK_H
